### ISSUE TITLE
Install instructions out of date?

### ISSUE THREAD

**Issue by tarcus69** [john-doherty/raspberry-pi-mjpeg-server#6]
Hello, I thought I'd quickly try this on Buster, AKA Debian 10. Unfortunately there are a lot of missing or broken installation steps.

First of all, NPM is not installed by default;

```
npm install raspberry-pi-mjpeg-server --save
bash: npm: command not found

```
So I apt-get install that and re-run the install;
```
sudo apt-get install npm
npm install raspberry-pi-mjpeg-server --save
```
This does not look happy;
```
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN notice [SECURITY] braces has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=braces&version=1.8.5 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ raspberry-pi-mjpeg-server@1.0.3
added 178 packages from 110 contributors in 34.783s
```
And indeed it isn't:
```
pi@raspberrypi:~ $ node raspberry-pi-mjpeg-server.js -w 1280 -l 1024
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/pi/raspberry-pi-mjpeg-server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
Is there any chance of supplying more comprehensive installation instructions as it seems the simple NPM command is not enough?

**Comment by andyryan** [comment]
Have you tried a different version of node?
